### ISSUE TITLE
Membership Product Quantity

### ISSUE THREAD

**Issue by chaotic234** [magefox/membership#11]
Ive started experiencing this bug after the update. I'm unable to adjust the quantity on a membership product.

To reproduce
1. Catalog > Products > Create Membership Product
2. Filled out details
3. Purposely left qty at 0 but made sure its in stock
4. Set membership dates, and group
5. Saved and closed.
6. Went back to edit the membership product to change Qty
7. Saved and Qty didn't change

What i expected to happen was the qty of the product was suppose to change like any other simple product created in Magento 2.2.1

Im on Mac OS X 10.10.5, Firefox 62.0.3

**Comment by vanthinh87** [comment]
I have fixed this issue, please check this merge request and update to your site. We will add this hotfix to next version as soon as possible.
https://github.com/magefox/membership/commit/84b5207417960aad5e7d561d9f9592eb59071b9c

Thanks
